### ISSUE TITLE
have you used any of the us states topojson files with datamaps?

### ISSUE THREAD

**Issue by mg1075** [yooper/open-model#1]
Hello, 

It looks like these topojson files could be useful, but I am getting an error in attempts to use with datamaps (saw your blog post). Have you used any of these topojson files with datamaps?

I get an error in the console. 

Uncaught TypeError: Cannot read property 'type' of undefined
topojson, line 219

**Comment by yooper** [comment]
I have always opted to use the geo.json files because they are half the size of the topojson files. Maybe if you can provide more information about the error on line 219 and what data file you are trying to use, we could debug the issue.

**Comment by mg1075** [comment]
I thought one of the advantages of using a topojson file is the smaller file size for topojson?
For example, compare the file sizes of Alabama (as displayed in your repo): 
geojson: 128.819 kb
topojson: 22.715 kb

**Comment by yooper** [comment]
Sorry, I got them mixed up. It has been a while since I used these data sets.
